### ISSUE TITLE
Erorrs when running via SDK

### ISSUE THREAD

**Issue by Fmstrat** [herosilas12/OpenRGB-python-FX#2]
Hi,

In Ubuntu 20.04, I've installed OpenRBG from the `deb` here: https://gitlab.com/CalcProgrammer1/OpenRGB/-/releases/release_0.5

I then installed OpenRGB SDK:
```
pip3 install openrgb-python
```

Then I tried to run `Chase.py`:
```
$ python3 Chase.py --C1 255 0 0 --C2 0 255 0
Traceback (most recent call last):
  File "Chase.py", line 4, in <module>
    client = openrgb.OpenRGBClient()
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/orgb.py", line 267, in __init__
    self.comms.requestDeviceNum()
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/network.py", line 175, in requestDeviceNum
    self.read()
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/network.py", line 113, in read
    self.callback(device_id, packet_type, buff[0])
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/orgb.py", line 281, in _callback
    self.comms.requestDeviceData(x)
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/network.py", line 168, in requestDeviceData
    self.read()
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/network.py", line 132, in read
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data, self._protocol_version))
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/utils.py", line 459, in unpack
    start, metadata = MetaData.unpack(data, version, start)
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/utils.py", line 406, in unpack
    start, val = parse_string(data, start)
  File "/home/fmstrat/.local/lib/python3.8/site-packages/openrgb/utils.py", line 94, in parse_string
    val = struct.unpack(f"{size}s", data[start:start + size])[0].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
```

The server is running and the SDK Client that's part of the OpenRGB GUI connects fine.

Any ideas how to proceed?

**Comment by Fmstrat** [comment]
Looks like this is unrelated to here, and is OpenRGB related. Being discussed here: https://discord.com/channels/699861463375937578/709998213310054490
